openapi: 3.1.0
info:
  title: splat token
  description: |-
    splat token
  version: 1.0.0
servers:
  - url: https://proxy-ql-splat-report.netlify.app
  - url: http://localhost:8888

paths:
  /api.yaml:
    get:
      tags:
        - schema
  /api/proxy-ql:
    post:
      tags:
        - api
      description: |-
        This endpoint proxies the request body and some headers as is to splatnet API `/graphql` in order to bypass browser CORS restrictions.  

        Requires bullet token as Authorization Bearer header value.
      security:
        - bearerAuth: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              additionalProperties: true
              examples:
                - extensions:
                    persistedQuery:
                      version: 1
                      sha256Hash: "b24d22fd6cb251c515c2b90044039698aa27bc1fab15801d83014d919cd45780"
                  "variables": {}
        required: true

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []
