[build]
publish = "site/"
edge_functions = "./edge-functions"

[[headers]]
for = "/v2/*"
[headers.values]
Access-Control-Allow-Origin = "*"
Allow = "OPTIONS,POST"

[[edge_functions]]
path = "/api/proxy-ql"
function = "proxy-ql"
