[build]
publish = "site/"
edge_functions = "./edge-functions"

[[headers]]
for = "/v2/*"
[headers.values]
Allow = "OPTIONS,POST"
Access-Control-Allow-Origin = "*"
Access-Control-Allow-Headers = "*"

[[edge_functions]]
path = "/api/proxy-ql"
function = "proxy-ql"
