[build]

edge_functions = "./edge-functions"

[functions]
deno_import_map = "./import_map.json"


[[redirects]]
from = "https://proxy-ql-splat-report.netlify.app/*"
to = "https://proxy-ql.splat.report/:splat"
status = 301
force = true

[[redirects]]
from = "https://main--proxy-ql-splat-report.netlify.app/*"  # [main] is a branch name
to = "https://proxy-ql.splat.report/:splat"
status = 301
force = true

[[headers]]
for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "OPTIONS, HEAD, POST"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Max-Age = "86400"

[[edge_functions]]
path = "/api/proxy-ql"
function = "proxy-ql"
